### ISSUE TITLE
[1w]任务 讨论/交付/展示

### ISSUE THREAD

**Issue by cnfeat** [OpenMindClub/OMOOCHacker#11]
- 作业交付示例：
  - [作业](https://github.com/OpenMindClub/OMOOCHacker/blob/master/1sGit/Version2.1.doc)  
  - [笔记](https://github.com/OpenMindClub/OMOOCHacker/blob/master/1sGit/Git.md)
- 规则说明:
  - 附上自己本周作业的提交文件的链接
  - 附上一篇自己的课堂笔记，分享自己在上完本次课与完成作业过程中的收获及感想(选做)

请在 2wd2 19:42 前回复本 issue 提交你的本周作业

---
- 讨论参考: 
  - [典章:说与菜鸟 | PyChina.org Static Wiki](http://wiki.pychina.org/hd/FreshProposeFor.html)
  - [提问的智慧](http://wiki.woodpecker.org.cn/moin/AskForHelp)
    - [5W1H](http://wiki.woodpecker.org.cn/moin/5W1H)
    - [SMART原则 - MBA智库百科](http://wiki.mbalib.com/wiki/SMART%E5%8E%9F%E5%88%99)
  - ...
- 技术讨论一定要认真的提供可以复现问题的足够信息
- 否则其他人是无法用脑补来还原你的场景的
- 特此草拟如下提问模板,以便学员使用:

:

```
## 背景
- 系统:
- 版本:
- 代码:
- ...

## 现象
- 输入: ..
- 触发: ..
- 问题: 非期待...

## 分析
- 尝试0:
    - 参考:
    - 判断:
    - 实验:
    - 结论:
- 尝试1:
- ...

## 方案
- 解决思路0:
    - 参考:
    - 设想:
- 解决思路1:
...

哪种思路正确,或是其它思路?
```

**Comment by libiqin** [comment]
[1wHW](https://github.com/libiqin/OMOOCHacker/blob/master/2nMarkdown/1wHW-Creme-Bru%CC%82le%CC%81e.md)

Bonjour！

**Comment by picklecai** [comment]
# 问题：引用文字后的有序列表如何继续正常计数

## 背景
- 系统: win8
- 版本: Mark的ownPad 2 free版

## \- 代码:
1. 引用  
   
   > 这是引用文字。快捷键是Ctrl+Q。   
   > 
   > > 「春天花会开。鸟儿自由自在…… 」她说，「他唱这个到底是什么意思呢？『躲猫猫』？ 」  
   > > 2015.10 By pickle    
2. 代码  
   # 代码快捷键是Ctrl+K。
   
   def main():  
       print "This is main program."

## 现象
- 有序列表是：3.引用4.代码。 
- 现象1：  
  在3.引用下，引用的最后一行文字。如果文字后加一行空行，则4.代码的显示效果为1.代码（有序列表从头开始计数）。  
  2.现象2：  
  如果文字后不加一行空行，则4.代码也变成引用格式。  
- 现象3：  
  注：引用的最后一行文字，最后加两个空格，不改变显示结果。  
- 现象4：  
  以上3个操作是在MarkdownPad2里。现在在Github网页中，3.引用前加了分割线，显示是正常的。即“3.引用，空格，4.代码” 显示为“1.引用，空格，2.代码”。引用正常，有序列表也正常。  

## 分析
- 现象4:  
  这可能是个例外，因为加这个分割线，在正常文件里很奇怪，这里是为了表示以下内容和上面不同来源才用的（似乎也应该用引用，但下面也是引用，乱套了。）这个操作在MarkdownPad2里并不这样显示。  

## 求问
- 现象1和现象2的矛盾如何解决？

fork了仓库。作业还在本地练习，所以还没有提交到库里去啊。

上传成功，地址：https://github.com/picklecai/OMOOCHacker/blob/master/2nMarkdown/Ex1.md

在浏览器端看是正常的，在MarkdownPad2里就是上述现象。

@Azeril 突然发现这是提交作业的issue，我这个提交是提问！

**Comment by Azeril** [comment]
@picklecai 先 fork 课程仓库再提交 提交作业请看置顶的规则...你这样 让人很难办啊

**Comment by picklecai** [comment]
fork了仓库。作业还在本地练习，所以还没有提交到库里去啊。

**Comment by susansecret** [comment]
[homework_WK1](https://github.com/susansecret/OMOOCHacker/blob/master/2nMarkdown/Markdown%20syntax%20rules_susansecret.md)

**Comment by picklecai** [comment]
突然发现这是提交作业的issue，我上一个提交是提问！

**Comment by sunnyhuang42** [comment]
> 突然发现这是提交作业的issue，我上一个提交是提问！

可以提交疑问的,这是 [1w]任务 讨论/交付/展示 issue @picklecai

**Comment by Azeril** [comment]
@picklecai 你这提问 太像不需要解答的自问自答了...上传成功就好啦

**Comment by liyaokaka** [comment]
[作业](https://github.com/liyaokaka/OMOOCHacker/blob/master/2nMarkdown/work.md)

**Comment by douzhipin** [comment]
[作业和笔记](https://github.com/douzhipin/OMOOCHacker/blob/master/2nMarkdown/%E3%80%8C%E5%83%8F%E9%BB%91%E5%AE%A2%E4%B8%80%E6%A0%B7%E5%88%9B%E4%BD%9C%E3%80%8D%E8%AF%BE%E7%A8%8B%E7%AC%94%E8%AE%B0.markdown)

之前在微信群问的问题我也把他写到笔记里面了，用office的方式去用MD，产生的错误。

**Comment by junjielizero** [comment]
[作业](https://github.com/junjielizero/OMOOCHacker/blob/master/2nMarkdown/homework.md)，用了以下五种Markdown语法：
- 粗体
- 标题
- 链接
- 引用
- 列表

**Comment by stepsame** [comment]
[homework](https://github.com/stepsame/OMOOCHacker/blob/master/2nMarkdown/homework.md)

**Comment by ouyangzhiping** [comment]
@douzhipin  赞思考！多练习多写代码，就明白新手与专家的区别了。

**Comment by benafrant** [comment]
[homework](https://github.com/benafrant/OMOOCHacker/blob/master/2nMarkdown/Markdown%20%E5%AD%A6%E4%B9%A0%E6%97%A5%E5%BF%97.md)
**整合第二周学习笔记和预习笔记**

**Comment by benafrant** [comment]
[像黑客一样创作·学习日志](https://github.com/benafrant/OMOOCHacker/blob/master/2nMarkdown/%E5%83%8F%E9%BB%91%E5%AE%A2%E4%B8%80%E6%A0%B7%E5%88%9B%E4%BD%9C%C2%B7%E5%AD%A6%E4%B9%A0%E6%97%A5%E5%BF%97.md)

**Comment by chaonet** [comment]
[homework](https://github.com/chaonet/OMOOCHacker/blob/master/2nMarkdown/Markdown.md)

**Comment by xiaoxiaodexin** [comment]
[作业](https://github.com/xiaoxiaodexin/OMOOCHacker/blob/master/2nMarkdown/作业2.md)

**Comment by complexly** [comment]
[作业](https://github.com/complexly/OMOOCHacker/blob/master/2nMarkdown/%E9%9A%90%E7%A7%A9%E5%BA%8F.md)

**Comment by cherryPotter** [comment]
[第二次作业](https://github.com/cherryPotter/OMOOCHacker/blob/master/2nMarkdown/Markdown2.md)

**Comment by ralphjsquare** [comment]
[交作业](https://github.com/ralphjsquare/OMOOCHacker/blob/master/2nMarkdown/1wHw-A%20Sef-Introduction%20to%20Markdown%20-ralphjsquare.md)

**Comment by Time-lady** [comment]
[作业](https://github.com/Time-lady/OMOOCHacker/blob/master/2nMarkdown/Markdown.md)

**Comment by sunmmy** [comment]
[作业：Markdown 教程](https://github.com/sunmmy/OMOOCHacker/blob/master/2nMarkdown/introductiontomarkdown.md)

**Comment by sophialuan** [comment]
[homework](https://github.com/sophialuan/OMOOCHacker/blob/master/1w_homework.md)

**Comment by linxiafenggu** [comment]
[作业](https://github.com/linxiafenggu/OMOOCHacker/blob/master/2nMarkdown/Homework.md)

**Comment by sisisimao** [comment]
[作业](https://github.com/sisisimao/OMOOCHacker/blob/master/2nMarkdown/2015-11-03-why-do-not-students-like-school.md)

**Comment by AwThink** [comment]
[homework](https://github.com/AwThink/OMOOCHacker/blob/master/2nMarkdown/FEnote.md)

**Comment by nirvanafish** [comment]
[作业](https://github.com/nirvanafish/OMOOCHacker/blob/master/2nMarkdown/sleep.md)

**Comment by badboy315** [comment]
[homework](https://github.com/badboy315/OMOOCHacker/blob/master/2nMarkdown/Markdown2.md)

老文章交作业

**Comment by Wangqiaoyang** [comment]
[作业](https://github.com/Wangqiaoyang/OMOOCHacker/blob/master/2nMarkdown/2w_md_review.md)

**Comment by Azeril** [comment]
@libiqin @picklecai @susansecret @xiaoxiaodexin @douzhipin 确认已提交并完成作业。douzhipin 的困惑和自我解答的过程不错啦 很多时候就是要有这样的折腾劲才能掌握一个工具或一门手艺。
关于空格 的确是如此。行尾空格 只有两个空格才能换行。换段则是行尾两个空格加换一段与直接换一段是一样的效果。在列表中 只能实现前者。因为一旦使用换段 列表形态受制于语法 很容易就被打乱了...

**Comment by Azeril** [comment]
@junjielizero @stepsame @liyaokaka @benafrant @chaonet 确认提交并完成作业。
benafrant 和 chaonet 同学用的语法相当全面。 liyaokaka 则使用了 表格 的语法形式 也不错。
不过 benafrant 注意啦 引用不要乱用...在引用模式里各种套用列表容易让页面显得很乱的 XD
chaonet 的语法手册相当简洁有力！而且还有萌图 哈哈

**Comment by Azeril** [comment]
@xiaoxiaodexin 确认。列表很清晰 语法要点都涵盖啦 
@complexly  确认。书评好评
@cherryPotter 确认。用到了三级列表的知识 很不错啦
@ralphjsquare 确认。内容涵盖很全面 很完整的一个语法教程。不过有几张图的链接标点估计错了或链接本身有点问题 所以没显示出来。
@Time-lady 确认。主要知识点列的很清楚。图的显示也有一点问题。

**Comment by Azeril** [comment]
@sunmmy 确认。能够重拾并发现一个东西的好 就是本次课程的一个很重要的启示啦 哈哈 语法列表很完善（除了没有图片的那一块知识点）。
@sophialuan 现学现用 就拿来做第一次课的笔记整理了 干得漂亮啦 最后镇帖的章鱼猫好评
@linxiafenggu 第二位将语法用于书评的 嗯~ 图片居中的语法也掌握啦 不错
@sisisimao 多图文排版很好 还 got 到了 GFM 的删除线语法 四毛干得很棒~
@AwThink 确认。嗯 用到了很多下代码区块及行内代码引用的知识。整理的也蛮清晰。

**Comment by Azeril** [comment]
@badboy315 我也建议把 Mou 换成 Macdown ！开发者众筹后来就没影子了 现在留下一个半坏不坏的 Mou 提供下载 简直无良...
@Wangqiaoyang 确认。语法基本都涵盖了。就是图没正确显示 咦 乔阳一天里交了两周的作业 干得漂亮...
@nirvanafish 啊啊 最喜欢你这篇了~ 我不会告诉你原先打算用于演示的例子 是我快速生成一篇如何制作糖醋排骨的文章吧...清晰而明确 很棒 头图和主题都太有爱 XD

**Comment by Rainvoo** [comment]
rainvoo [作业](https://github.com/Rainvoo/OMOOCHacker/blob/master/2nMarkdown/2nd_homework.md)

**Comment by Yinying** [comment]
迟交作业，补上。
[homework](https://github.com/Yinying/Yinying.github.io/blob/master/_posts/2015-11-23-build-jekyll-blog.md)

**Comment by Azeril** [comment]
@Rainvoo 收到。图片显示不出来...
@Yinying 作业已收到。是的 在中国使用一些命令进行软件包的下载和安装时 遇到网络问题的概率比遇到命令错误导致的更...还有像权限请求也是蛮多的 gem 安装时 包括 homebrew 安装时 都有需要用 sudo 命令才行

**Comment by xpgeng** [comment]
[作业](https://github.com/xpgeng/OMOOCHacker/blob/master/2nMarkdown/Markdown.md)

**Comment by sunnyhuang42** [comment]
过期关闭
