### ISSUE TITLE
[Hb] OMHacker 内测课程整体说明

### ISSUE THREAD

**Issue by sunnyhuang42** [OpenMindClub/OMOOCHacker#3]
### 课程节奏

~ 每周循环，不断探索练习
- 课程节奏:
  - *wd0 同侪互助，提交作业
  - *wd1 休整，小结前周
  - *wd2 课程直播：19:42~22:42
  - *wd3 新任务接手，尝试实践
  - *wd4 继续实践
  - *wd5 总结经验，交流互助
  - *wd6 线下聚会，同侪互助，提交作业
- 课程要求:
  - 每天投入 42 mins
  - 每周投入 5+ 小时
  - 整体 42+ 小时的全情投入
  - 达到:
    - 熟练使用 Markdown 写作
    - 学会使用 gitbook 发布笔记
    - 独立搭建独立博客发布文字
    - 懂得运用 github 进行协作
    - 使用简单的命令行
    - ……
### 课程大纲
- 0w:Git 与 GitHub 
- 1w:Markdown
- 2w:Jekyll 
- 3w:Sublime/TextMate 
- 4w:Linux Command Line Interface (CLI) Fundamentals  
- 5w:GitBook 
- 6w:……
- 7w:……

PS:课程中将邀请一位知名黑客做嘉宾分享，敬请期待！
### 课程交互通道
1. 课程直播: 斗鱼
2. 课程提问讨论/任务提交: [Issues · OpenMindClub/OMOOCHacker](https://github.com/OpenMindClub/OMOOCHacker/issues)
3. 课程回放/任务领取: 芝麻星(权限待配置)
4. 课程重要通告发布: [OMOOCHacker 学员邮件列表](https://groups.google.com/forum/#!forum/omoochacker)
5. 日常讨论/通告提醒: OMOOCHacker 微信群
### 开课检查清单

~ 为正常进入课程节奏，请逐一确认自己已经获得以下权限:
1. 加入GitHub & [OMHacker · OpenMindClub Team](https://github.com/orgs/OpenMindClub/teams/omhacker) （请及时登陆 GitHub 同意加入邀请）
2. 进入 OMOOCHacker 微信群
3. 加入[OMOOCHacker 学员邮件列表](https://groups.google.com/forum/#!forum/omoochacker)（收到 「您已加入“OMOOCHacker”」标题的邮件，证明已加入成功。若检索标题、翻遍垃圾箱后都未收到，请邮件联系 omooc@openmind.club ）
4. 进入芝麻星（权限待配置）

过程若遇到困难，请微信联系 一休(微信号 aiopenmind)。

**Comment by ZoomQuiet** [comment]
2015-10-31 10:38 GMT+08:00 ishanshan <notifications@github.com>:
>
> OMHacker 内测课程整体说明
>
> 课程节奏
>
> ~ 每周循环，不断探索练习
>
...
> 课程要求:
>
> 每天投入 42 mins
> 每周投入 5+ 小时
> 整体 42+ 小时的全情投入

...

看起来好眼熟...

**Comment by sunnyhuang42** [comment]
归档
