### ISSUE TITLE
[video]第一课 Git 与 GitHub 录播视频

### ISSUE THREAD

**Issue by cnfeat** [OpenMindClub/OMOOCHacker#5]
## 新鲜出炉的录播来了
- （1）课程介绍：http://t.cn/RUJrdwu
- （2）github 网页版演示介绍：http://t.cn/RUJrDqk
- （3）github 桌面版演示介绍：http://t.cn/RUJdhxV
- （4）github 命令行演示：http://t.cn/RUJdeHx
## 知识点补充：

比较重要的知识点 除了今天后边讲的 Git 命令的操作之外 提示一下别的核心知识。

理解 Git 与 GitHub 的操作，要明白 Git 作为版本控制工具 它的操作流程，实际上 Git 是分三大区域的，虽然我们就只看到一个文件夹而已

我们操作的当前文件夹就是 Git 概念里的工作区，也叫 Working Directory，如果对文件做了改动、增加或删除或修改，虽然当前的文件夹形态是直接变化的，但 Git 仓库它必须要接受命令后才能知道，具体是要怎么操作，这时候的命令是 $ git add file_name 或 $ git add .

在完成这一步后，修改的文件会被记录到 Git 仓库的暂存区。这个暂存区的意思就相当于一个缓冲带，可以往前 就是进入 正式仓库，可以回退，对于仓库不会有改动

此外，完成添加到仓库的行动后，文件只是被存放在本地的 git 仓库中 如果我们要和远程的 git 仓库同步 就需要用到 git push (推送)的命令。如果本地仓库与远程仓库还没连接 则要用到 git remote add origin git@url… 的命令 完成连接。git clone 也就是下载下来的仓库 可以直接进行同步（也就是推送 git push）

这个核心知识点如果大家掌握了 那无论使用 客户端版本还是用 git 命令行 都很容易啦

**Comment by junjielizero** [comment]
> get clone 也就是下载下来的仓库 可以直接进行同步（也就是推送 git push）

是git clone吧

**Comment by Azeril** [comment]
@junjielizero 笔误呐 ><

**Comment by cnfeat** [comment]
视频已全部在芝麻星发布,关闭此 issue
