### ISSUE TITLE
[0w] 任务 交付/展示

### ISSUE THREAD

**Issue by Azeril** [OpenMindClub/OMOOCHacker#7]
本周的作业内容:
- Fork [OMOOCHacker ](https://github.com/OpenMindClub/OMOOCHacker) 仓库
  - 未完成仓库 fork 的同学请尽快呐~
- 将仓库中 1sGit 文件夹下的 4 个 Version.doc文件,依版本顺序合并为一个文件
- 合并后,提交推送到自己仓库中
- 完成后，提交作业链接到本 issue 页面

作业交付示例：
- [作业](https://github.com/OpenMindClub/OMOOCHacker/blob/master/1sGit/Version2.1.doc) 
- [笔记](https://github.com/OpenMindClub/OMOOCHacker/blob/master/1sGit/Git.md)

规则说明:
- 附上自己本周作业的提交文件的链接
- 附上一篇自己的课堂笔记，分享自己在上完本次课与完成作业过程中的收获及感想(选做)
- 如果你还不熟悉 Markdown，可直接附上文件链接

请在 1wd2 19:42 前回复本 issue 提交你的本周作业

**Comment by stepsame** [comment]
- [homework](https://github.com/stepsame/OMOOCHacker/blob/master/1sGit/Version.doc)

**Comment by yuyandong** [comment]
## 对作业要求有 2 个小疑问

因为审题不明，自问自答，还是没有解决，故在此提出疑问`Q`  和所尝试 `A`

### 疑问 1
-  Q 1 : `依版本顺序合并` 是怎么个形式？我不明白 "依版本顺序合并" 所指...

> 将仓库中 1sGit 文件夹下的 4 个 Version.doc 文件, 依版本顺序合并为一个文件
- A 1 : 难道是 用 page 修改 v1.0-->v1.1--->v2.0--->v2.1 ? 

然后 `git rm` 删除 ？+`git commit -am "combines to Version2.1.doc"`  + `git push`  打完收工 ?

_PS 0 : 如果是这般做法， *_合并*\* 何在？*

### 疑问 2
- Q 2 : 命令行中使用`git merge-file` 命令合并 四个文件为一个？
- A 2 : 因为 `git clone`  fork到本地的库没有历史缓存，没有文件更改历史，`git HEAD^` 掉不回头。

如果是git 命令合并分支好说，可是用git 命令合并文件（课堂没有提到），初以为 `git merge-file`可以 

可是

> git-merge-file - Run a **three-way file** merge. //第三方啊
> 
> git merge-file incorporates all changes that lead from the `<base-file>`to `<other-file>`into`<current-file>`. The result ordinarily goes into`<current-file>`. git merge-file is useful for combining separate changes to an original. Suppose`<base-file>` is the original, and both `<current-file>`and`<other-file>` are modifications of `<base-file>`, then git merge-file combines both changes.

4个文件又都是本地同一个文件夹的, 且没有历史缓存// 4个文件是一起`clone` 的，`git diff` 查看不会显示变化 。

> git merge-file README.my README README.upstream
> combines the changes of README.my and README.upstream since README, tries to merge them and writes the result into README.my.//把从原初文件`READEME` 增减过的 `REAME.upstream` 里的内容写入 `REASME.my` 

难道是这样吗? 
试试吧，不过还是不同情况，走不通。。。
出现错误提醒 `Cannot merge binary files` 

### 后记

因为希望能在`git`命令对比 .doc 的（二进制）文件，经过多方查、验最终实现对 Word 文档进行版本控制。 

[详见折腾笔记](https://github.com/yuyandong/OMOOCHacker/tree/master/1sGit)

_PS 1 :不至于在一开始作业就挖这个坑吧——可以弃坑了——不然试验本地修改v1-v2-v3-v4（checkout多个branch) ,push 到 远程仓库进行测试——已然超出本次课程授课内容_

**Comment by chaonet** [comment]
- [homework](https://github.com/chaonet/OMOOCHacker/blob/master/1sGit/Version.doc)
- [notes](https://github.com/chaonet/OMOOCHacker/blob/master/1sGit/Git.md)

**Comment by badboy315** [comment]
## 0w
- [homework](https://github.com/badboy315/OMOOCHacker/blob/master/1sGit/Version2.1.doc)
- [notes](https://github.com/badboy315/OMOOCHacker/blob/master/1sGit/Git.md)

**Comment by guopeikun** [comment]
### 作业提交
- [HomeWork1](https://github.com/guopeikun/OMOOCHacker/blob/master/1sGit/HomeWork1.doc)

**Comment by Yinying** [comment]
作业链接：[homework](https://github.com/Yinying/OMOOCHacker/commits/master/1sGit/hw.doc)

**Comment by complexly** [comment]
[作业](https://github.com/complexly/OMOOCHacker/blob/master/1sGit/Version.doc)

**Comment by liyaokaka** [comment]
[作业](https://github.com/liyaokaka/OMOOCHacker/commits/master/1sGit/Version.doc)

**Comment by Azeril** [comment]
@yuyandong 嗯 实际上你把整个问题复杂化了。这个问题的解决只需要用到第一次课中提及的最基本的 git add—git commit—git push 命令 或基于图形界面的操作都可以搞定。

本题的目的不在于合并文件 而是合并版本。比方说 我写一篇东西 在这个过程中会有修改 对于不同时间的修改 我可能会保存多个不同的版本。这时 依照一般形式来说 一个版本就是以一个文件的形态存在。于是有了不止一个的文件。

在这一题里也是一样的道理。实际上 多个文件是一个文件在不同时期的副本。最终版本为最新的那个。而我们要做的是 如何使最新的文档拥有可以追溯原先版本的能力。

不要试图只通过命令行或图形界面来搞定 因为你涉及到文本的修改 还是需要用到 诸如 word 或 任务管理器（或 Finder ）一类的东西的。

因而 这个作业不需要用到 git merge 或 rm 这样的命令。并没有那么复杂。

:P

**Comment by Azeril** [comment]
@stepsame @chaonet @badboy315 @guopeikun @Yinying @complexly 大家都好棒 完成本周作业时都及时切换了视角 提交的作业都正确无误~
@liyaokaka 同学 思路没问题 不过不知什么情况 最终文件我无法直接在 GitHub 正常查看。也算通过 因为本次更多是对于基础内容的掌握 会提交就好啦。

另外再赞一下 chaonet 和 yuyandong 同学的学习笔记  折腾的劲很不容易。chaonet 同学还将 Git 更深层次的命令也学了 很棒

**Comment by junjielizero** [comment]
[作业提交](https://github.com/junjielizero/OMOOCHacker/commits/master/1sGit)

**Comment by zhuzuojun** [comment]
[homework](https://github.com/zhuzuojun/OMOOCHacker/tree/master/1sGit)

**Comment by cherryPotter** [comment]
[homework](https://github.com/cherryPotter/OMOOCHacker/commits/master/1sGit/Version.doc)

**Comment by Time-lady** [comment]
[homework](https://github.com/Time-lady/OMOOCHacker/commits/1e833359a7732088133d30da233a8b9353f5cf32/1sGit/homework.doc)  
话说我是直接把那个version1~4复制粘贴重命名，然后每次都删掉原来的homework，保存一个新的homework。因为我一打开doc文件里面编辑的话保存时候就变成page文件，汗，不仅是git小白还是mac小白。没有安装office，只有一个很山寨的word app 不给力啊。然后在图形客户端里操作的还蛮简单。命令行回头再试一下，老是出错。命令行用惯了估计会很快很高效，不过还是习惯图形界面。老师的意思算是理解了。其实老师直接说让大家创建一个文档，修改三次提交三次不就完事儿了嘛，搞这么复杂，容易把人绕晕。这是从结果去回溯啊，不如从开始往下一步步走，来的顺。

**Comment by sisisimao** [comment]
[作业](https://github.com/sisisimao/OMOOCHacker/blob/master/1sGit/Version.doc)

**Comment by leokaikai** [comment]
OMOOCHacker/1sGit/Version.doc

**Comment by leokaikai** [comment]
https://github.com/leokaikai/OMOOCHacker/commits/master/1sGit/Version.doc

**Comment by leokaikai** [comment]
https://github.com/leokaikai/OMOOCHacker/commits/master/1sGit/Version.doc

@Time-lady 我跟你的情况是一样一样的，没有装word，所以都是把1.0——2.1的四个作业改成version然后提交，删掉然后把下一个改成version再提交

**Comment by leokaikai** [comment]
- [homework](https://github.com/leokaikai/OMOOCHacker/commits/master/1sGit/Version.doc)

**Comment by douzhipin** [comment]
[作业](https://github.com/douzhipin/OMOOCHacker/blob/master/1sGit/Version.doc)

**Comment by EchoYao1210** [comment]
- [homework](https://github.com/EchoYao1210/OMOOCHacker/blob/master/1sGit/Version%20Final.doc)

**Comment by sophialuan** [comment]
- [homework](https://github.com/sophialuan/learngit/tree/master/%E4%BD%9C%E4%B8%9A)

**Comment by benafrant** [comment]
- [作业](https://github.com/benafrant/OMOOCHacker/blob/master/1sGit/Version2.2.doc)

**Comment by linxiafenggu** [comment]
[作业](https://github.com/linxiafenggu/OMOOCHacker/blob/master/1sGit/Homework.doc

**Comment by linxiafenggu** [comment]
[作业](https://github.com/linxiafenggu/OMOOCHacker/blob/master/1sGit/Homework.doc)

**Comment by linxiafenggu** [comment]
* [作业](https://github.com/linxiafenggu/OMOOCHacker/blob/master/1sGit/Homework.doc

**Comment by linxiafenggu** [comment]
- [作业](https://github.com/linxiafenggu/OMOOCHacker/blob/master/1sGit/Homework.doc)

**Comment by linxiafenggu** [comment]
@Time-lady @leokaikai 在Pages中选择：“文件”-“导出到”-“Word”，即可保存Word格式的文件。

**Comment by mac-naxin** [comment]
- [作业](https://github.com/mac-naxin/OMOOCHacker/blob/master/1sGit/Version.doc)

**Comment by Azeril** [comment]
@junjielizero @linxiafenggu @leokaikai @EchoYao1210 @douzhipin @mac-naxin 作业提交并完成准确。不容易啊 XD

**Comment by cherryPotter** [comment]
@Azeril 没有明确点名回复的，默认是指作业不正确吗？

**Comment by Azeril** [comment]
@Time-lady 有个小问题 你在第三次推送时已经把最终版本整合了 后边又撤销了 所以少了两个版本的样子...还有 提交时写的说明 请用英文描述 英文是填写 commit 描述的准确语言 这个切记...
@cherryPotter 提交并且可以回溯版本 不过呐 有个小问题 你跳过了 2.0 版本的文件 ....
@zhuzuojun 原先的word 文档怎么变成 md 了....不过思路是对的
@sisisimao 提交记录里 除了删除原文档外 好像就只有提交了最新版本的 git 记录？
@sophialuan Sophia 你的作业有两个状况 第一 作业是在 fork 的基础上去完成的 不是自己另建的个人仓库 第二 你的作业文档目前版本是 2.0 不是最新版的 2.1。不过 已经学会本地创建和关联远程仓库 还是不错啦
@benafrant 版本回溯时 2.0 已经是 2.1 的文档了... 思路对

**Comment by Azeril** [comment]
@cherryPotter :cake: 不要着急...

**Comment by nirvanafish** [comment]
- [作业](https://github.com/nirvanafish/OMOOCHacker/blob/master/1sGit/Version.doc)
  我似乎刚好把楼上的@mac-naxin同学修改过的仓库fork过来了，所以先回溯了历史到@Azeril的版本，在此基础上修改后push发生冲突，再用--no-ff模式merge了远程仓库，重新add、commit、push自己的Version.doc文件。绕了一大圈子，不知道还有别的解决办法么？

**Comment by Azeril** [comment]
@nirvanafish 你可以删除原先 fork 的仓库 再重新 fork 不影响的

**Comment by Azeril** [comment]
@nirvanafish 作业已确认 完成得很好 而且会用 merge 来更新本地仓库 很棒啦

**Comment by cherryPotter** [comment]
@Azeril 感谢Azeril老师。跳过v2.0确实太粗心勒，commit之后老忘记push。

期待今晚课程。

**Comment by Cen74** [comment]
[作业](https://github.com/Cen74/OMOOCHacker/commits/master/1sGit/Version.doc)
中间错了几次，用git reset又回到初始状态，在git push -f。git push -f 好像不应该经常使用。

**Comment by libiqin** [comment]
[Homework](https://github.com/libiqin/OMOOCHacker/blob/master/1sGit/0wHW_RL.doc)

**Comment by susansecret** [comment]
[susansecret's homework_WK1](https://github.com/susansecret/OMOOCHacker/blob/master/1sGit/HW_WK1.doc)

**Comment by Azeril** [comment]
@susansecret @Cen74 @libiqin 提交并确认 作业完成啦

**Comment by Silencetodd** [comment]
[Homework 1st](https://github.com/Silencetodd/OMOOCHacker/blob/master/1sGit/Version2.2.1.doc)

**Comment by ralphjsquare** [comment]
https://github.com/ralphjsquare/OMOOCHacker/tree/master/1sGit   是这样么。。

**Comment by xiaoxiaodexin** [comment]
作业：https://github.com/xiaoxiaodexin/OMOOCHacker/blob/master/1sGit/Version1.doc

**Comment by xiaoxiaodexin** [comment]
作业：https://github.com/xiaoxiaodexin/OMOOCHacker/blob/master/1sGit/Version1.doc

**Comment by AwThink** [comment]
[作业](https://github.com/AwThink/OMOOCHacker/tree/master/1sGit)

**Comment by Wangqiaoyang** [comment]
[作业](https://github.com/Wangqiaoyang/OMOOCHacker/blob/master/1sGit/Version.doc)

**Comment by Azeril** [comment]
@ralphjsquare @Wangqiaoyang @AwThink 确认提交作业并且完成正确。不过 ralphjsquare 伊迭请注意 提交时填写的描述 如果有差异 把差异也写出来 尽量不要在提交时都用一样的描述。不然回溯 包括我查看时都容易不明就里。这方面 乔阳的描述中对于版本的差异记录得就很清晰明白 哪怕用的字数也差不多。

@xiaoxiaodexin 提交的版本有问题 并且最终提交的文档也不对啊 结果应当是与最新版本的文档一致的 只不过可以回溯先前版本的历史而已...
@Silencetodd 确认已提交 但是版本方面有点问题 少了一个可以回溯的版本呐。

**Comment by Rainvoo** [comment]
rainvoo [作业](https://github.com/Rainvoo/OMOOCHacker/blob/master/1sGit/1sGit_homework1s.doc)

**Comment by xpgeng** [comment]
[作业](https://github.com/xpgeng/OMOOCHacker/blob/master/1sGit/Version.doc)
- 这作业是不是交得也太晚了.. 还请Az老师开恩呐! ;-)

**Comment by xpgeng** [comment]
[作业](https://github.com/xpgeng/OMOOCHacker/blob/master/1sGit/Version.doc)
- 作业交的很晚. .. 辛苦Az. ;-)

**Comment by sunnyhuang42** [comment]
过期关闭
